apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-deployment
  labels:
    app: realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld
  #where we create pods
  template:
    metadata:
      labels:
        app: realworld
    #configs deployment to create pods with realworld image
    spec:
      containers:
      - name: realworld
        image: demo:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "10.0.2.205"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "realworld_db"
        - name: DB_USER
          valueFrom: 
           secretKeyRef:
            name: mysql-secret
            key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysql-secret
            key: mysql-password 
---

apiVersion: v1
kind: Service
metadata:
  name: realworld-service
spec:
  type: LoadBalancer
#service selects pods to forward the requests to
  selector:
    app: realworld #should match labels
  ports:
    - protocol: TCP
      port: 3000 #sets port of the sevice
      targetPort: 3200 #which port to forward the request to pods
      nodePort: 30100